//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Лаба_1.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class spravochniki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public spravochniki()
        {
            this.uchetnaya = new HashSet<uchetnaya>();
        }
    
        public int id_schet { get; set; }
        public string full_name { get; set; }
        public string aadress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<uchetnaya> uchetnaya { get; set; }
    }
}
